# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
    - task: Docker@2
      inputs:
        containerRegistry: 'devsuperappregistry'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'Azure subscription 1(dd568595-5cd6-440e-bac6-3e52bc422ed6)'
        appType: 'webAppLinux'
        WebAppName: 'devSuperApp'
        packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
