# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  imageName: 'devsuperappregistry.azurecr.io/container_for_image:$(Build.BuildId)'
  azureSubscription: '0676b297-0bb7-4596-856b-6297ae465035'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
   
- stage: Add
  displayName: Add to container
  jobs:
  - job: Add
    steps:
    - task: Docker@2
      displayName: Add to container
      inputs:
        containerRegistry: 'devsuperappregistry'
        repository: 'container_for_image'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'

- stage: Deploy
  displayName: Container Deploy to Azure Web App
  jobs:
  - job: Deploy
    steps:
    - task: AzureWebAppContainer@1
      displayName: Azure Web App on Container Deploy
      inputs:
        appName: 'devSuperApp'
        azureSubscription: $(azureSubscription)
        imageName: $(imageName)
